import type { AccessibilityIssue } from './types';

export const DEMO_HTML = `<!doctype html>
<html>
<head>
  <title>Report</title>
  <style>
    *{box-sizing:border-box}body{margin:0;color:#18313a;background:#f7faf8;font-family:Arial,sans-serif}.city-header{display:flex;align-items:center;justify-content:space-between;padding:18px 32px;background:#0c393d;color:#fff}.seal-wrap{display:flex;align-items:center;gap:12px;font-weight:700}.seal-wrap img{width:42px;height:42px;border-radius:50%;object-fit:cover}.city-nav{display:flex;align-items:center;gap:20px;font-size:13px}.menu-button{border:1px solid rgba(255,255,255,.45);background:transparent;color:#fff;border-radius:5px;padding:6px 9px}.report-shell{max-width:920px;margin:0 auto;padding:54px 42px 80px}.kicker{color:#287c73;font-size:11px;font-weight:700;letter-spacing:.12em;text-transform:uppercase}.report-shell h3{margin:10px 0 10px;font-size:36px;letter-spacing:-.04em;color:#102b32}.lede{max-width:660px;color:#5b6c70;line-height:1.65}.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin:28px 0}.stat{padding:18px;border:1px solid #d3dfdc;background:#fff;border-radius:8px}.stat strong{display:block;font-size:26px;color:#08786d}.stat span{font-size:11px;color:#63777b}.section{margin-top:36px}.section h5{font-size:19px;margin-bottom:10px}.chart{height:170px;display:flex;align-items:end;gap:24px;padding:22px 28px 20px;background:#e9f2ee;border-radius:10px}.bar{width:54px;background:#118578;border-radius:4px 4px 0 0}.bar:nth-child(1){height:95px}.bar:nth-child(2){height:128px}.bar:nth-child(3){height:78px}.bar:nth-child(4){height:54px}.chart-note{color:#9da7a4;font-size:12px}.energy-table{width:100%;border-collapse:collapse;background:white}.energy-table td{padding:12px;border:1px solid #d9e2df;text-align:left}.energy-table tr:first-child{background:#123d40;color:white;font-weight:700}.report-cta{display:inline-block;margin-top:22px;padding:10px 14px;border-radius:6px;background:#0b7168;color:#fff;cursor:pointer}.newsletter{margin-top:42px;padding:24px;background:#133d41;color:white;border-radius:10px}.newsletter h5{margin:0 0 7px}.newsletter p{margin:0 0 18px;color:#c9dbd9;font-size:13px}.newsletter input{min-height:40px;border:0;border-radius:5px;padding:8px;margin-right:6px}.newsletter button{min-height:40px;border:0;border-radius:5px;background:#7ee0c7;color:#0a3635;font-weight:700;padding:0 14px}.consent{display:block;margin-top:12px;color:#c9dbd9;font-size:11px}.footer{padding:24px 32px;background:#092d30;color:#d5e3e1;font-size:11px}.project-map{width:100%;height:80px;border:0;background:#dce8e5}
  </style>
</head>
<body>
  <header class="city-header">
    <div class="seal-wrap"><img data-node-id="city-seal" src="/og.png"><span>City of Arbor Creek</span></div>
    <nav class="city-nav"><span>Programs</span><span>Data</span><span>Residents</span><button class="menu-button" data-node-id="menu-button">☰</button></nav>
  </header>
  <div class="report-shell" data-node-id="report-shell">
    <span class="kicker">Office of Sustainability</span>
    <h3 data-node-id="report-title">2026 Community Energy Report</h3>
    <p class="lede">A public overview of how Arbor Creek is reducing municipal energy use and investing in resilient neighborhoods.</p>
    <section class="stats" id="stats">
      <div class="stat"><strong>17%</strong><span>less energy use</span></div>
      <div class="stat"><strong>42</strong><span>city buildings upgraded</span></div>
      <div class="stat"><strong>$3.1M</strong><span>community savings</span></div>
    </section>
    <section class="section" id="stats"><h5 data-node-id="summary-heading">Executive summary</h5><p>Arbor Creek used 17% less energy than last year, led by building efficiency upgrades and lower residential demand.</p></section>
    <section class="section" aria-labelledby="missing-heading"><h5 data-node-id="chart-heading">Energy by sector</h5>
      <div class="chart" data-node-id="energy-chart" role="img"><span class="bar"></span><span class="bar"></span><span class="bar"></span><span class="bar"></span></div>
      <p class="chart-note" data-contrast="fail">2023–2026 municipal energy use, indexed to the 2023 baseline.</p>
    </section>
    <section class="section"><h5>Annual consumption</h5><table class="energy-table" data-node-id="energy-table"><tr><td>Sector</td><td>2025 MWh</td><td>2026 MWh</td></tr><tr><td>Municipal</td><td>18,400</td><td>15,900</td></tr><tr><td>Residential</td><td>62,100</td><td>49,800</td></tr><tr><td>Commercial</td><td>38,700</td><td>35,200</td></tr></table></section>
    <div class="report-cta" data-node-id="report-cta" role="button">Download report</div>
    <p>For the complete methodology and neighborhood data, <a data-node-id="download-link" href="#download">click here</a>.</p>
    <section class="newsletter" data-node-id="newsletter-region"><h5 id="newsletter-heading">Community energy updates</h5><p>Monthly project news and public meeting notices.</p><form><input data-node-id="email-input" type="email" placeholder="Email address"><button>Go</button><span class="consent"><input data-node-id="consent-input" type="checkbox"> Receive monthly updates</span></form></section>
    <iframe class="project-map" data-node-id="project-map" src="about:blank"></iframe>
  </div>
  <footer class="footer">City of Arbor Creek · Public Information Office</footer>
</body>
</html>`;

const issue = (value: AccessibilityIssue) => value;

export const ISSUE_CATALOG: AccessibilityIssue[] = [
  issue({id:'keyboard-cta',ruleId:'keyboard-role-button',title:'Report download is mouse-only',description:'A custom button cannot be reached or activated from the keyboard.',wcagCriterion:'2.1.1',wcagLevel:'A',severity:'critical',category:'keyboard',selector:'[data-node-id="report-cta"]',elementHtml:'<div role="button">Download report</div>',explanation:'People who navigate without a mouse cannot reach this control.',suggestedFix:'Use a native link with the report destination.',confidence:.99,requiresHumanReview:false,decision:'safe-auto-fix'}),
  issue({id:'email-label',ruleId:'label',title:'Newsletter email field has no label',description:'The email field relies on placeholder text instead of a persistent label.',wcagCriterion:'1.3.1',wcagLevel:'A',severity:'critical',category:'forms',selector:'[data-node-id="email-input"]',elementHtml:'<input type="email" placeholder="Email address">',explanation:'Screen readers cannot reliably announce the field purpose, and placeholders disappear while typing.',suggestedFix:'Associate a visible Email address label with the field.',confidence:.98,requiresHumanReview:false,decision:'safe-auto-fix'}),
  issue({id:'lang',ruleId:'html-has-lang',title:'Document language is missing',description:'The html element does not identify the page language.',wcagCriterion:'3.1.1',wcagLevel:'A',severity:'serious',category:'language',selector:'html',elementHtml:'<html>',explanation:'Assistive technology may pronounce content using the wrong language rules.',suggestedFix:'Set lang="en" on the html element.',confidence:.99,requiresHumanReview:false,decision:'safe-auto-fix'}),
  issue({id:'main',ruleId:'landmark-one-main',title:'Main landmark is missing',description:'Primary report content is wrapped in a generic div.',wcagCriterion:'1.3.1',wcagLevel:'A',severity:'serious',category:'structure',selector:'[data-node-id="report-shell"]',elementHtml:'<div class="report-shell">',explanation:'Landmarks let screen reader users move directly to primary content.',suggestedFix:'Use a main element for the report content.',confidence:.97,requiresHumanReview:false,decision:'safe-auto-fix'}),
  issue({id:'menu-name',ruleId:'control-name',title:'Menu button has no accessible name',description:'The navigation toggle is announced only as a symbol.',wcagCriterion:'4.1.2',wcagLevel:'A',severity:'serious',category:'aria',selector:'[data-node-id="menu-button"]',elementHtml:'<button>☰</button>',explanation:'The button purpose is not communicated to screen reader users.',suggestedFix:'Add an accessible name: Open site menu.',confidence:.96,requiresHumanReview:false,decision:'safe-auto-fix'}),
  issue({id:'chart-alt',ruleId:'non-text-content',title:'Energy chart needs a meaningful description',description:'The chart has no text alternative and its takeaway requires context.',wcagCriterion:'1.1.1',wcagLevel:'A',severity:'serious',category:'images',selector:'[data-node-id="energy-chart"]',elementHtml:'<div role="img">…bars…</div>',explanation:'The trend and comparison are unavailable to people who cannot see the chart.',suggestedFix:'Describe the chart’s intended takeaway and connect that description to the chart.',confidence:.49,requiresHumanReview:true,decision:'human-review-required',reviewQuestion:'What should users understand from this chart?',reviewOptions:['Energy consumption decreased 17% compared with last year.','Residential use fell faster than other sectors.','Describe every chart value.','Enter my own interpretation.']}),
  issue({id:'table-headers',ruleId:'table-headers',title:'Data table has no header cells',description:'The first row uses data cells instead of column headers.',wcagCriterion:'1.3.1',wcagLevel:'A',severity:'serious',category:'tables',selector:'[data-node-id="energy-table"] tr:first-child',elementHtml:'<tr><td>Sector</td><td>2025 MWh</td>…</tr>',explanation:'Screen readers cannot announce the relationship between values and their columns.',suggestedFix:'Use th elements with scope="col".',confidence:.94,requiresHumanReview:false,decision:'safe-auto-fix'}),
  issue({id:'heading-order',ruleId:'heading-order',title:'Heading hierarchy skips levels',description:'The report starts at heading level 3 and sections use level 5.',wcagCriterion:'1.3.1',wcagLevel:'A',severity:'moderate',category:'structure',selector:'[data-node-id="report-title"]',elementHtml:'<h3>…</h3> → <h5>…</h5>',explanation:'An inconsistent outline makes the page structure harder to understand and navigate.',suggestedFix:'Use h1 for the report title and h2 for its sections.',confidence:.94,requiresHumanReview:false,decision:'safe-auto-fix'}),
  issue({id:'generic-link',ruleId:'link-purpose',title:'Download link text is ambiguous',description:'The link says “click here” without describing its destination.',wcagCriterion:'2.4.4',wcagLevel:'A',severity:'moderate',category:'links',selector:'[data-node-id="download-link"]',elementHtml:'<a>click here</a>',explanation:'Links are often navigated out of context, where generic wording has no meaning.',suggestedFix:'Use a purpose-specific label based on what the link downloads.',confidence:.62,requiresHumanReview:true,decision:'human-review-required',reviewQuestion:'What will happen when this link is activated?',reviewOptions:['Download the 2026 energy dataset.','Open the full report methodology.','View neighborhood-level findings.','Enter my own description.']}),
  issue({id:'seal-alt',ruleId:'non-text-content',title:'City seal has no text alternative',description:'The seal image has no alt attribute.',wcagCriterion:'1.1.1',wcagLevel:'A',severity:'moderate',category:'images',selector:'[data-node-id="city-seal"]',elementHtml:'<img src="/og.png">',explanation:'The image may communicate identity, or it may be decorative; that intent requires a human decision.',suggestedFix:'Choose a concise identity description or mark the image decorative.',confidence:.55,requiresHumanReview:true,decision:'human-review-required',reviewQuestion:'Does the city seal convey identity, or is it decorative?',reviewOptions:['It identifies the City of Arbor Creek.','It is decorative beside the city name.','It conveys an official city publication.','Enter my own interpretation.']}),
  issue({id:'aria-reference',ruleId:'aria-reference-valid',title:'ARIA reference points to a missing element',description:'A report section references an ID that does not exist.',wcagCriterion:'4.1.2',wcagLevel:'A',severity:'moderate',category:'aria',selector:'[aria-labelledby="missing-heading"]',elementHtml:'<section aria-labelledby="missing-heading">',explanation:'Assistive technology cannot resolve the intended accessible name.',suggestedFix:'Point aria-labelledby to the existing chart section heading.',confidence:.95,requiresHumanReview:false,decision:'safe-auto-fix'}),
  issue({id:'contrast',ruleId:'color-contrast',title:'Chart note has insufficient contrast',description:'The note uses light gray text against a pale background.',wcagCriterion:'1.4.3',wcagLevel:'AA',severity:'moderate',category:'color',selector:'[data-contrast="fail"]',elementHtml:'<p class="chart-note">…</p>',explanation:'Low contrast can make explanatory text unreadable for people with low vision.',suggestedFix:'Use the darker slate token and manually verify rendered contrast.',confidence:.84,requiresHumanReview:false,decision:'agent-proposal'}),
  issue({id:'table-caption',ruleId:'table-caption',title:'Consumption table has no caption',description:'The data table does not identify its overall purpose.',wcagCriterion:'1.3.1',wcagLevel:'A',severity:'moderate',category:'tables',selector:'[data-node-id="energy-table"]',elementHtml:'<table>…</table>',explanation:'A concise caption helps people understand the data before navigating cell by cell.',suggestedFix:'Add a human-confirmed caption describing the comparison.',confidence:.64,requiresHumanReview:true,decision:'human-review-required',reviewQuestion:'What comparison should this table communicate?',reviewOptions:['Annual energy consumption by sector.','2025 and 2026 megawatt-hours by sector.','Progress toward the city reduction target.','Enter my own interpretation.']}),
  issue({id:'consent-label',ruleId:'label',title:'Newsletter consent checkbox has no label',description:'Nearby consent text is not programmatically associated.',wcagCriterion:'3.3.2',wcagLevel:'A',severity:'moderate',category:'forms',selector:'[data-node-id="consent-input"]',elementHtml:'<input type="checkbox"> Receive monthly updates',explanation:'The checkbox is announced without its purpose.',suggestedFix:'Wrap the control and text in a label.',confidence:.96,requiresHumanReview:false,decision:'safe-auto-fix'}),
  issue({id:'doc-title',ruleId:'document-title',title:'Document title is too generic',description:'The title is “Report” and does not identify the content.',wcagCriterion:'2.4.2',wcagLevel:'A',severity:'minor',category:'structure',selector:'title',elementHtml:'<title>Report</title>',explanation:'A specific title helps users identify the page in tabs, history, and search.',suggestedFix:'Use the report and city name.',confidence:.95,requiresHumanReview:false,decision:'safe-auto-fix'}),
  issue({id:'duplicate-id',ruleId:'duplicate-id',title:'Duplicate stats ID',description:'Two sections use id="stats".',severity:'minor',category:'aria',selector:'#stats',elementHtml:'id="stats" × 2',explanation:'Duplicate identifiers can break labels, references, and navigation.',suggestedFix:'Generate stable unique IDs and update references.',confidence:.89,requiresHumanReview:false,decision:'agent-proposal'}),
  issue({id:'region-name',ruleId:'region-name',title:'Newsletter region has no accessible name',description:'A repeated content region is not named.',wcagCriterion:'1.3.1',wcagLevel:'A',severity:'minor',category:'structure',selector:'[data-node-id="newsletter-region"]',elementHtml:'<section class="newsletter">',explanation:'Named regions make landmark navigation predictable.',suggestedFix:'Label the region with its existing heading.',confidence:.92,requiresHumanReview:false,decision:'safe-auto-fix'}),
  issue({id:'iframe-title',ruleId:'iframe-title',title:'Project map frame has no title',description:'The embedded project map is not named.',wcagCriterion:'4.1.2',wcagLevel:'A',severity:'minor',category:'other',selector:'[data-node-id="project-map"]',elementHtml:'<iframe src="about:blank">',explanation:'Users need a title to decide whether to enter or skip an embedded frame.',suggestedFix:'Use “Map of municipal energy projects” if that purpose is confirmed.',confidence:.88,requiresHumanReview:false,decision:'agent-proposal'}),
];

export const ISSUE_BY_ID = Object.fromEntries(ISSUE_CATALOG.map((item) => [item.id, item])) as Record<string, AccessibilityIssue>;
export const SAFE_ISSUE_IDS = ISSUE_CATALOG.filter((item) => item.decision === 'safe-auto-fix').map((item) => item.id);
export const HUMAN_REVIEW_IDS = ISSUE_CATALOG.filter((item) => item.requiresHumanReview).map((item) => item.id);
